# Deterministic signal threshold placeholders for later implementation.
OPEN_BLOCKERS_RED_THRESHOLD = 0
HIGH_SEVERITY_BUGS_RED_THRESHOLD = 1
SCOPE_CHURN_RED_THRESHOLD = 0.20
SCOPE_CHURN_YELLOW_THRESHOLD = 0.10
REOPEN_RATE_RED_THRESHOLD = 0.15
