import ast
from datetime import UTC, datetime
from pathlib import Path

from app.services.report_document_models import (
    ChartSpec,
    ReportDocument,
    ReportSection,
)
from app.services.report_pdf_renderer import SimplePdfRenderer
from app.services.reporting_service import SimplePdfRenderer as CompatiblePdfRenderer


SERVICES_DIRECTORY = Path(__file__).resolve().parents[1] / "app" / "services"


def test_pdf_renderer_has_no_database_or_template_dependencies() -> None:
    source = (SERVICES_DIRECTORY / "report_pdf_renderer.py").read_text(
        encoding="utf-8"
    )
    module = ast.parse(source)
    imported_modules = {
        node.module
        for node in ast.walk(module)
        if isinstance(node, ast.ImportFrom) and node.module is not None
    }
    imported_modules.update(
        alias.name
        for node in ast.walk(module)
        if isinstance(node, ast.Import)
        for alias in node.names
    )

    assert "sqlalchemy" not in imported_modules
    assert not any(name.startswith("app.repositories") for name in imported_modules)
    assert "app.services.reporting_service" not in imported_modules
    assert not any("template" in name for name in imported_modules)


def test_reporting_service_preserves_pdf_renderer_import_compatibility() -> None:
    assert CompatiblePdfRenderer is SimplePdfRenderer


def test_pdf_rendering_is_deterministic_and_escapes_embedded_content() -> None:
    generated_at = datetime(2026, 7, 21, 10, 30, tzinfo=UTC)
    document = ReportDocument(
        title=r"Release (deterministic) \ report",
        subtitle="LHPM | REL-1",
        entity_id="REL-1",
        generated_at=generated_at,
        version="1.2.3",
        sections=(
            ReportSection(
                title="Summary",
                lines=("Stable content",),
                rows=(("Status", "Ready"),),
                bullets=("Keep deterministic output",),
                charts=(
                    ChartSpec(
                        title="Confidence",
                        kind="line",
                        points=(("First", 50.0), ("Latest", 75.0)),
                        y_max=100,
                        value_suffix="%",
                    ),
                ),
            ),
        ),
    )

    first = SimplePdfRenderer(
        generated_at=generated_at,
        version=document.version,
    ).render(document)
    second = SimplePdfRenderer(
        generated_at=generated_at,
        version=document.version,
    ).render(document)

    assert first == second
    assert first.startswith(b"%PDF-1.4")
    assert first.endswith(b"%%EOF\n")
    assert b"Release \\(deterministic\\) \\\\ report" in first
    assert b"BI /W" in first
    assert b"/F [/AHx /Fl]" in first


def test_pdf_renderer_paginates_large_documents_with_numbered_footers() -> None:
    generated_at = datetime(2026, 7, 21, tzinfo=UTC)
    document = ReportDocument(
        title="Long report",
        subtitle="Pagination boundary",
        entity_id="long-report",
        generated_at=generated_at,
        version="1.0.0",
        sections=(
            ReportSection(
                title="Evidence",
                lines=tuple(f"Evidence line {index}" for index in range(100)),
            ),
        ),
    )

    pdf = SimplePdfRenderer(
        generated_at=generated_at,
        version=document.version,
    ).render(document)

    assert pdf.count(b"/Type /Page ") >= 3
    assert b"Generated by LighthousePM | Page 1" in pdf
    assert b"Generated by LighthousePM | Page 2" in pdf
    assert b"xref\n" in pdf
    assert b"startxref\n" in pdf
